# Generated by Django 3.2 on 2022-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloggedinsession',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userloggedinsession',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='LoggedinToken',
        ),
    ]
