version: '3.7'
services:
  django_jwt:
    volumes:
      - static:/static
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_jwt

volumes:
  static: